log_level: info
http:
    port: 8080
    host: ""
    documentation: false
files:
    set_perms: false
    create_dirs: false
    originals_dir: img/originals
    cache_dir: img/cached
    clear_on_start: false
    populate_from: ""
cache_rules:
    max_objects: 100000
    max_size: 500 GB
image_defaults:
    format: jpeg
    quality_jpeg: 80
    quality_gif: 256
    width: 0
    height: 800
    max_size: 1 MB
    interpolation: nearestNeighbor
image_presets:
    - name: thumbnail
      alias:
        - thumb
        - th
      format: jpeg
      quality: 80
      width: 150
      height: 150
      max_size: 10 KB
      interpolation: lanczos3
    - name: small
      alias:
        - small
        - s
      width: 0
      height: 400
    - name: medium
      alias:
        - medium
        - m
      width: 0
      height: 800
    - name: large
      alias:
        - large
        - l
      width: 0
      height: 1600
