logging: debug
http:
    port: 8080
    host: ""
files:
    clean_start: true
    populate_from: test-fs/originals
    paths:
        originals: img/originals
        cache: img/cache
        set_perms: true
        create_dirs: true
    cache:
        num: 5
        size: 1 MB
default_image_preset:
    alias:
        - default
        - def
    format: jpeg
    quality_jpeg: 80
    quality_gif: 256
    width: 800
    height: 0
    max_size: 1 MB
    resize: ""
image_presets:
    - name: default thumbnail
      alias:
        - thumb
        - th
      format: jpeg
      quality: 80
      width: 100
      height: 100
      max_size: 10 KB
      resize: ""
    - name: default small
      alias:
        - small
        - sm
        - s
      format: jpeg
      quality: 80
      width: 400
      height: 0
      max_size: 30 KB
      resize: ""
